FROM goldy/tor-hidden-service
#RUN  apt-get update&& apt-get upgrade && apt-get install libseccomp-dev

#RUN mkdir -p /var/lib/tor/hidden_service/vpn/authorized_clients/ && \
#echo descriptor:x25519:33RYW3AJ4TRQDTOCVGY4HLZVBWZZ6UVVNL4SWQJEL5MOZNGEEQCQ > /var/lib/tor/hidden_service/vpn/authorized_clients/1.auth